apiVersion: v1
kind: Service
metadata:
  name: auth-microservice-svc
  labels:
    app: auth-microservice
spec:
  selector:
    app: auth-microservice
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP