apiVersion: v1
kind: Service
metadata:
  name: saggia-auth-svc
  labels:
    app: saggia-auth
spec:
  selector:
    app: saggia-auth
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP