apiVersion: apps/v1
kind: Deployment
metadata:
  name: saggia-auth
  labels:
    app: saggia-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saggia-auth
  template:
    metadata:
      labels:
        app: saggia-auth
    spec:
      containers:
      - name: saggia-auth
        image: adilsonfuxe/saggia-auth
        env:
          - name: MONGO_URL
            value: mongodb://mongodb:27017/authDb
        ports:
          - containerPort: 5050